## Choose scientifically representative a sample for airline_final dataset

In [1]:
# import required librairies
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
# read the initial dataset
airline_data = pd.read_csv('/Users/rodneydavermann/Desktop/final-project/airline_final')
airline_data.head(2)
df = airline_data.drop('Unnamed: 0', axis=1)
df.head(1)

,mkt_ccode,dep_airport,cancel_code,arr_airport,day_week_name,month__name,route,mkt_fl_no,date,dep_delay_time_actual,arr_delay_time_actual,mins_late_delay_code_e_carrier,mins_late_delay_code_f_weather,mins_late_delay_code_g_nas,mins_late_delay_code_h_security,mins_late_delay_code_i_late_arr_flight,delay
0,DL,BNA,0,MSP,Mon,Jan,BNA-MSP,3975,2022-01-24,36,50,36,0,14,0,0,1

In [6]:

# Divide the dataset into strata based on a categorical variable, e.g. 'category'
strata = df['mkt_ccode'].unique()

# Define the sample size, e.g. 10,000 rows
sample_size = 20000

# Initialize an empty dataframe to hold the sampled data
df_sample = pd.DataFrame()

# Iterate over each stratum and sample a proportional number of rows from each stratum
for s in strata:
    df_stratum = df[df['mkt_ccode'] == s]
    n_stratum = len(df_stratum)
    sample_stratum_size = int(sample_size * (n_stratum / len(df)))
    df_stratum_sample = df_stratum.sample(n=sample_stratum_size, random_state=42)
    df_sample = pd.concat([df_sample, df_stratum_sample])

# Save the sampled data to a new CSV file
df_sample.to_csv('large_dataset_sampled.csv', index=False)

In [9]:
df_sample.head(2)
df_sample.shape

(19994, 17)

In [10]:
df_sample.describe()

,mkt_fl_no,dep_delay_time_actual,arr_delay_time_actual,mins_late_delay_code_e_carrier,mins_late_delay_code_f_weather,mins_late_delay_code_g_nas,mins_late_delay_code_h_security,mins_late_delay_code_i_late_arr_flight,delay
count,19994.000000,19994.000000,19994.000000,19994.000000,19994.000000,19994.000000,19994.000000,19994.000000,19994.000000
mean,2537.414124,12.319196,7.417925,5.479294,0.864109,2.359158,0.055467,5.168501,0.362259
std,1733.416272,53.163271,56.636417,34.399658,15.090556,15.533700,2.617035,29.689486,0.480665
min,1.000000,-30.000000,-62.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1105.000000,-5.000000,-14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2214.000000,-1.000000,-5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3820.750000,9.000000,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,8800.000000,1560.000000,1553.000000,1553.000000,953.000000,936.000000,208.000000,1360.000000,1.000000

In [11]:
df_sample.isnull().sum()

mkt_ccode                                 0
dep_airport                               0
cancel_code                               0
arr_airport                               0
day_week_name                             0
month__name                               0
route                                     0
mkt_fl_no                                 0
date                                      0
dep_delay_time_actual                     0
arr_delay_time_actual                     0
mins_late_delay_code_e_carrier            0
mins_late_delay_code_f_weather            0
mins_late_delay_code_g_nas                0
mins_late_delay_code_h_security           0
mins_late_delay_code_i_late_arr_flight    0
delay                                     0
dtype: int64

In [12]:
df_sample.columns

Index(['mkt_ccode', 'dep_airport', 'cancel_code', 'arr_airport',
       'day_week_name', 'month__name', 'route', 'mkt_fl_no', 'date',
       'dep_delay_time_actual', 'arr_delay_time_actual',
       'mins_late_delay_code_e_carrier', 'mins_late_delay_code_f_weather',
       'mins_late_delay_code_g_nas', 'mins_late_delay_code_h_security',
       'mins_late_delay_code_i_late_arr_flight', 'delay'],
      dtype='object')

In [17]:
cat_sample = ['dep_airport', 'cancel_code', 'arr_airport','day_week_name', 'month__name', 'route']


cols = df_sample[cat_sample].columns
cols

for col in cols:
    unique_values = df_sample[col].unique()
    print(f"The unique values of {col} are {unique_values}")

The unique values of dep_airport are ['EWR' 'CHO' 'DCA' 'MSY' 'SLC' 'JFK' 'MCO' 'ATL' 'BOS' 'IAD' 'CHA' 'DTW'
 'LGA' 'PDX' 'IND' 'TPA' 'CLT' 'ORD' 'MSP' 'PIT' 'LAS' 'ORF' 'BUF' 'RSW'
 'SJC' 'MLU' 'CLE' 'ABE' 'ONT' 'SEA' 'LAX' 'CVG' 'MKE' 'HSV' 'GPT' 'BIL'
 'GRR' 'ELP' 'SMF' 'GEG' 'GRB' 'BHM' 'SAN' 'PBI' 'OAK' 'CHS' 'GSP' 'SGU'
 'HNL' 'CAE' 'SYR' 'MIA' 'AUS' 'BWI' 'SAT' 'FCA' 'JAX' 'RIC' 'CMH' 'DFW'
 'BNA' 'SFO' 'IAH' 'MYR' 'TUS' 'OMA' 'DAL' 'BGR' 'MEM' 'SAV' 'GTR' 'TYS'
 'MLB' 'ALB' 'ABY' 'JAN' 'ANC' 'MSN' 'RDU' 'MCI' 'FLL' 'BRD' 'GTF' 'SJU'
 'HIB' 'ROC' 'GSO' 'FSD' 'BIS' 'ECP' 'MFR' 'TUL' 'MVY' 'PNS' 'STT' 'HOU'
 'AEX' 'PSP' 'ATW' 'CDC' 'ABQ' 'PHL' 'MSO' 'AGS' 'DHN' 'EYW' 'PVD' 'STL'
 'BZN' 'SGF' 'SRQ' 'MDW' 'LAN' 'PIH' 'SNA' 'DEN' 'PHX' 'PWM' 'BDL' 'SDF'
 'SBN' 'LIT' 'LGB' 'MLI' 'IDA' 'VPS' 'BTM' 'MQT' 'GNV' 'BOI' 'TLH' 'BJI'
 'BUR' 'PSC' 'JAC' 'BTV' 'BQK' 'EKO' 'MOT' 'DAB' 'ACK' 'MOB' 'OKC' 'ABR'
 'SUN' 'TRI' 'TVC' 'CSG' 'RHI' 'XWA' 'HHH' 'DSM' 'ROA' 'OGG' 'BTR' 'APN'
 'FAR' 'ILM' 'AVL' 'RNO' 'DLH' 'SHV' 'LEX' 'BMI' 'MGM' 'FWA' 'RAP' 'LWS'
 'ICT' 'LFT' 'FAT' 'GFK' 'EUG' 'LSE' 'HPN' 'LIH' 'RST' 'INL' 'CWA' 'ELM'
 'JNU' 'VLD' 'HLN' 'CPR' 'DAY' 'CRW' 'EVV' 'RDM' 'XNA' 'CID' 'FAI' 'PLN'
 'ESC' 'CIU' 'MDT' 'ORH' 'KOA' 'OAJ' 'ROW' 'LRD' 'MHT' 'PGV' 'YUM' 'CMI'
 'TYR' 'GJT' 'SAF' 'FNT' 'MAF' 'STX' 'DRO' 'ACT' 'ASE' 'ABI' 'LCH' 'SBY'
 'SBP' 'DRT' 'AVP' 'GRK' 'SCE' 'AMA' 'CLL' 'MHK' 'LBB' 'ART' 'FLG' 'EWN'
 'COU' 'LAW' 'SPI' 'GGG' 'BRO' 'FLO' 'COS' 'MFE' 'BFL' 'EGE' 'SJT' 'FSM'
 'LYH' 'PIA' 'SPS' 'FAY' 'TOL' 'PHF' 'SBA' 'DBQ' 'BPT' 'STS' 'CRP' 'ITH'
 'AZO' 'CAK' 'GRI' 'MRY' 'GCK' 'TXK' 'HRL' 'HTS' 'PUW' 'KTN' 'CDV' 'YAK'
 'SIT' 'ADQ' 'BRW' 'YKM' 'GST' 'OME' 'WRG' 'BLI' 'AKN' 'SCC' 'PAE' 'RDD'
 'BET' 'ALW' 'DLG' 'PSG' 'EAT' 'BQN' 'PSE' 'CYS' 'CGI' 'LNK' 'PIB' 'PUB'
 'FOD' 'DVL' 'DEC' 'RKS' 'HDN' 'CNY' 'HOB' 'MEI' 'EAR' 'CKB' 'GUC' 'OTH'
 'GCC' 'PAH' 'PBG' 'LAR' 'GUM' 'PQI' 'SLN' 'LBF' 'VEL' 'ERI' 'JST' 'MBS'
 'MTJ' 'ALS' 'COD' 'BFF' 'MKG' 'DIK' 'JMS' 'RIW' 'JLN' 'OGS' 'TBN' 'HYS'
 'ISP' 'TTN' 'SWF' 'ILG' 'SFB' 'PGD' 'AZA' 'PIE' 'PVU' 'SCK' 'BLV' 'HGR'
 'RFD' 'PSM' 'LCK' 'USA' 'IAG' 'ITO' 'ACY' 'LBE']
The unique values of cancel_code are ['0' 'B' 'C' 'A' 'D']
The unique values of arr_airport are ['ATL' 'LGA' 'JFK' 'RNO' 'MSY' 'SLC' 'JAX' 'PNS' 'SFO' 'MSP' 'MCI' 'IND'
 'MCO' 'CLT' 'ORD' 'CHS' 'SNA' 'FWA' 'DTW' 'CLE' 'SYR' 'ALB' 'PIT' 'APN'
 'GSO' 'DCA' 'SEA' 'TYS' 'GRB' 'FLL' 'DEN' 'PSC' 'TWF' 'PBI' 'AUS' 'DSM'
 'JAN' 'BOS' 'LAX' 'EWR' 'STL' 'SAN' 'CVG' 'ILM' 'CAE' 'VPS' 'BWI' 'OKC'
 'SAT' 'CRW' 'BNA' 'EYW' 'HSV' 'TRI' 'MSN' 'SAV' 'ANC' 'MDW' 'CHO' 'CMH'
 'FSD' 'RDU' 'GPT' 'ACK' 'RSW' 'LFT' 'MKE' 'ABQ' 'PWM' 'ATW' 'CID' 'LSE'
 'ABE' 'DFW' 'BOI' 'PHX' 'ESC' 'HNL' 'ROC' 'FAT' 'PHL' 'DLH' 'TUL' 'OMA'
 'CSG' 'GEG' 'BUF' 'INL' 'MQT' 'MEM' 'IDA' 'SMF' 'BGR' 'TPA' 'MDT' 'TUS'
 'IAH' 'COS' 'MSO' 'RDM' 'SCE' 'LAS' 'RHI' 'PSP' 'GFK' 'MIA' 'GNV' 'DAY'
 'STT' 'DAL' 'RIC' 'ORF' 'MLI' 'SJC' 'SGF' 'MLB' 'ROA' 'FCA' 'MGM' 'CNY'
 'PDX' 'EUG' 'OAJ' 'MOT' 'ELP' 'CHA' 'ABR' 'PLN' 'HPN' 'DAB' 'BZN' 'GRR'
 'ONT' 'SJU' 'SHV' 'AEX' 'LIT' 'CIU' 'AVL' 'BQK' 'BDL' 'LEX' 'SDF' 'TVC'
 'SUN' 'MTJ' 'ECP' 'SGU' 'HLN' 'TLH' 'AZO' 'HIB' 'SRQ' 'PIH' 'BTV' 'ASE'
 'MFR' 'XNA' 'ICT' 'FAR' 'MLU' 'OGG' 'MBS' 'LGB' 'IMT' 'LIH' 'ABY' 'MOB'
 'IAD' 'JAC' 'PVD' 'BRD' 'AGS' 'GSP' 'OAK' 'DHN' 'BTR' 'MYR' 'HOU' 'BIL'
 'BJI' 'VLD' 'BHM' 'RST' 'CDC' 'GTF' 'FAI' 'SBN' 'KTN' 'CWA' 'BUR' 'GTR'
 'BIS' 'BMI' 'FAY' 'EVV' 'ITH' 'LAN' 'FSM' 'LYH' 'MHT' 'HRL' 'GRK' 'SWO'
 'SBA' 'ERI' 'GCK' 'GJT' 'SBP' 'YUM' 'SAF' 'MHK' 'BRO' 'MFE' 'LBB' 'KOA'
 'ART' 'COU' 'MAF' 'AVP' 'LRD' 'CLL' 'HTS' 'EWN' 'ROW' 'CMI' 'SJT' 'FNT'
 'FLG' 'BFL' 'MRY' 'CAK' 'PIA' 'SBY' 'ACT' 'PHF' 'EGE' 'ABI' 'LAW' 'GRI'
 'STX' 'AMA' 'HHH' 'TXK' 'DRT' 'RAP' 'GGG' 'TYR' 'SPS' 'DRO' 'CRP' 'ACV'
 'STS' 'LCH' 'BPT' 'ALO' 'PGV' 'HDN' 'DBQ' 'BET' 'YAK' 'PUW' 'JNU' 'BLI'
 'PAE' 'SIT' 'BRW' 'YKM' 'OTZ' 'CDV' 'DLG' 'PSG' 'ADQ' 'RDD' 'ALW' 'EAT'
 'OME' 'ADK' 'WRG' 'ORH' 'BQN' 'MKG' 'JMS' 'MEI' 'SHR' 'GUC' 'RIW' 'LNK'
 'XWA' 'HYS' 'PIB' 'EAU' 'EAR' 'MCW' 'PRC' 'CGI' 'PBG' 'COD' 'LBF' 'JST'
 'PQI' 'OGS' 'BFF' 'GCC' 'DIK' 'JLN' 'CKB' 'VCT' 'SPI' 'CMX' 'SUX' 'SHD'
 'SLN' 'LAR' 'SPN' 'ALS' 'FOD' 'BIH' 'DVL' 'DDC' 'TBN' 'VEL' 'OTH' 'PAH'
 'RKS' 'CYS' 'LWS' 'TTN' 'ISP' 'SWF' 'PIE' 'PGD' 'PVU' 'BLV' 'LCK' 'SFB'
 'RFD' 'AZA' 'PSM' 'SMX' 'IAG' 'SCK' 'USA' 'TOL' 'ITO' 'LBE' 'ACY']
The unique values of day_week_name are ['Wed' 'Sun' 'Thu' 'Tue' 'Sat' 'Fri' 'Mon']
The unique values of month__name are ['May' 'Apr' 'Feb' 'Jul' 'Jun' 'Mar' 'Aug' 'Sep' 'Jan']
The unique values of route are ['EWR-ATL' 'CHO-LGA' 'DCA-JFK' ... 'SLC-HOU' 'BNA-FLL' 'STL-MIA']